version: "3.8"

services:
    db:
        image: mariadb
        restart: always
        volumes:
            - ./docker/sql:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        environment:
            TZ: Asia/Tokyo
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin:latest
    #   restart: always
    #   depends_on:
    #     - db
    #   environment:
    #     - PMA_ARBITRARY=1
    #     - PMA_HOST=db
    #   ports:
    #     - 8080:80

    api:
        build: ./django
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 36000
        container_name: api
        volumes:
            - ./django:/code/api
        expose:
            - 8000
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - custom_network

    ui:
        build: ./vue
        command: npm run serve
        container_name: ui
        volumes:
            - ./vue:/code/ui
        expose:
            - 8080
        ports:
            - 8080:8080
        depends_on:
            - api
        networks:
            - custom_network

    nginx:
        build: ./docker/nginx
        container_name: nginx
        restart: always
        ports:
            - 81:80
        networks:
            - custom_network
        environment:
            TZ: Asia/Tokyo
            CLIENT_MAX_BODY_SIZE: 64M
    # code-server:
    #   image: ghcr.io/linuxserver/code-server
    #   container_name: code-server
    #   environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Asia/Tokyo
    #     - PASSWORD=Password1
    #   volumes:
    #     - .:/code
    #   ports:
    #     - 8888:8443
    #   restart: unless-stopped

volumes:
    db-data:


networks:
    custom_network:
        driver: bridge
