# This is a basic workflow to help you get started with Actions

name: remote ssh command

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: executing remote ssh commands using password
        uses: garygrossgarten/github-action-ssh@release
        with:
         command: cd ias-project-react && git reset --hard && git pull https://oauth2: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@github.com/daisukekubota0823/ias-project-react.git && 
                  sudo chmod -R 777 /home/iasgcp/ias-project-react && cd react && npm -v && npm i --force --save && npm run build && 
                  sudo rm -R /var/www/html-IAS/* && cp -r /home/iasgcp/ias-project-react/react/build/* /var/www/html-IAS/ && sudo chmod -R 777 /var/www/html-IAS &&
                  cd .. && docker-compose up -d
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         privateKey: ${{ secrets.GCP_SSH_PRIVATE_KEY}}
         script: whoami
